package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias", catalog = "suite", uniqueConstraints = @UniqueConstraint(columnNames = "IDPadre"))
public class Categorias implements java.io.Serializable {

	private Integer idcategoria;
	private Integer idpadre;
	private Set<Videos> videoses = new HashSet<Videos>(0);

	public Categorias() {
	}

	public Categorias(Integer idpadre, Set<Videos> videoses) {
		this.idpadre = idpadre;
		this.videoses = videoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCategoria", unique = true, nullable = false)
	public Integer getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(Integer idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "IDPadre", unique = true)
	public Integer getIdpadre() {
		return this.idpadre;
	}

	public void setIdpadre(Integer idpadre) {
		this.idpadre = idpadre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "containvideoscategia", catalog = "suite", joinColumns = {
			@JoinColumn(name = "IDCategoria", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDVideo", nullable = false, updatable = false) })
	public Set<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(Set<Videos> videoses) {
		this.videoses = videoses;
	}

}
