package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Channels generated by hbm2java
 */
@Entity
@Table(name = "channels", catalog = "suite")
public class Channels implements java.io.Serializable {

	private Integer idchannels;
	private int logicalChannelNumber;
	private String url;
	private String name;
	private String description;
	private String aspectRatio;
	private String quality;
	private String visibility;
	private String smallIcon;
	private String mediumIcon;
	private String largeIcon;
	private Set<Infochannels> infochannelses = new HashSet<Infochannels>(0);
	private Set<Parrilla> parrillas = new HashSet<Parrilla>(0);
	private Set<Epg> epgs = new HashSet<Epg>(0);
	private Set<Paquetes> paqueteses = new HashSet<Paquetes>(0);

	public Channels() {
	}

	public Channels(int logicalChannelNumber, String url, String name, String aspectRatio, String quality,
			String visibility, String smallIcon, String mediumIcon, String largeIcon) {
		this.logicalChannelNumber = logicalChannelNumber;
		this.url = url;
		this.name = name;
		this.aspectRatio = aspectRatio;
		this.quality = quality;
		this.visibility = visibility;
		this.smallIcon = smallIcon;
		this.mediumIcon = mediumIcon;
		this.largeIcon = largeIcon;
	}

	public Channels(int logicalChannelNumber, String url, String name, String description, String aspectRatio,
			String quality, String visibility, String smallIcon, String mediumIcon, String largeIcon,
			Set<Infochannels> infochannelses, Set<Parrilla> parrillas, Set<Epg> epgs, Set<Paquetes> paqueteses) {
		this.logicalChannelNumber = logicalChannelNumber;
		this.url = url;
		this.name = name;
		this.description = description;
		this.aspectRatio = aspectRatio;
		this.quality = quality;
		this.visibility = visibility;
		this.smallIcon = smallIcon;
		this.mediumIcon = mediumIcon;
		this.largeIcon = largeIcon;
		this.infochannelses = infochannelses;
		this.parrillas = parrillas;
		this.epgs = epgs;
		this.paqueteses = paqueteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDChannels", unique = true, nullable = false)
	public Integer getIdchannels() {
		return this.idchannels;
	}

	public void setIdchannels(Integer idchannels) {
		this.idchannels = idchannels;
	}

	@Column(name = "LogicalChannelNumber", nullable = false)
	public int getLogicalChannelNumber() {
		return this.logicalChannelNumber;
	}

	public void setLogicalChannelNumber(int logicalChannelNumber) {
		this.logicalChannelNumber = logicalChannelNumber;
	}

	@Column(name = "Url", nullable = false, length = 40)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "AspectRatio", nullable = false, length = 6)
	public String getAspectRatio() {
		return this.aspectRatio;
	}

	public void setAspectRatio(String aspectRatio) {
		this.aspectRatio = aspectRatio;
	}

	@Column(name = "Quality", nullable = false, length = 3)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "Visibility", nullable = false, length = 8)
	public String getVisibility() {
		return this.visibility;
	}

	public void setVisibility(String visibility) {
		this.visibility = visibility;
	}

	@Column(name = "SmallIcon", nullable = false, length = 50)
	public String getSmallIcon() {
		return this.smallIcon;
	}

	public void setSmallIcon(String smallIcon) {
		this.smallIcon = smallIcon;
	}

	@Column(name = "MediumIcon", nullable = false, length = 50)
	public String getMediumIcon() {
		return this.mediumIcon;
	}

	public void setMediumIcon(String mediumIcon) {
		this.mediumIcon = mediumIcon;
	}

	@Column(name = "LargeIcon", nullable = false, length = 50)
	public String getLargeIcon() {
		return this.largeIcon;
	}

	public void setLargeIcon(String largeIcon) {
		this.largeIcon = largeIcon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "channels")
	public Set<Infochannels> getInfochannelses() {
		return this.infochannelses;
	}

	public void setInfochannelses(Set<Infochannels> infochannelses) {
		this.infochannelses = infochannelses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "containparrichanels", catalog = "suite", joinColumns = {
			@JoinColumn(name = "IDChannels", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDParrilla", nullable = false, updatable = false) })
	public Set<Parrilla> getParrillas() {
		return this.parrillas;
	}

	public void setParrillas(Set<Parrilla> parrillas) {
		this.parrillas = parrillas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "channels")
	public Set<Epg> getEpgs() {
		return this.epgs;
	}

	public void setEpgs(Set<Epg> epgs) {
		this.epgs = epgs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "channelses")
	public Set<Paquetes> getPaqueteses() {
		return this.paqueteses;
	}

	public void setPaqueteses(Set<Paquetes> paqueteses) {
		this.paqueteses = paqueteses;
	}

}
