package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfochannelsId generated by hbm2java
 */
@Embeddable
public class InfochannelsId implements java.io.Serializable {

	private int idinfo;
	private int idchannels;
	private int idorganizacion;

	public InfochannelsId() {
	}

	public InfochannelsId(int idinfo, int idchannels, int idorganizacion) {
		this.idinfo = idinfo;
		this.idchannels = idchannels;
		this.idorganizacion = idorganizacion;
	}

	@Column(name = "IDInfo", nullable = false)
	public int getIdinfo() {
		return this.idinfo;
	}

	public void setIdinfo(int idinfo) {
		this.idinfo = idinfo;
	}

	@Column(name = "IDChannels", nullable = false)
	public int getIdchannels() {
		return this.idchannels;
	}

	public void setIdchannels(int idchannels) {
		this.idchannels = idchannels;
	}

	@Column(name = "IDOrganizacion", nullable = false)
	public int getIdorganizacion() {
		return this.idorganizacion;
	}

	public void setIdorganizacion(int idorganizacion) {
		this.idorganizacion = idorganizacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfochannelsId))
			return false;
		InfochannelsId castOther = (InfochannelsId) other;

		return (this.getIdinfo() == castOther.getIdinfo()) && (this.getIdchannels() == castOther.getIdchannels())
				&& (this.getIdorganizacion() == castOther.getIdorganizacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdinfo();
		result = 37 * result + this.getIdchannels();
		result = 37 * result + this.getIdorganizacion();
		return result;
	}

}
