package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Infochannels generated by hbm2java
 */
@Entity
@Table(name = "infochannels", catalog = "suite")
public class Infochannels implements java.io.Serializable {

	private InfochannelsId id;
	private Channels channels;
	private Organizacion organizacion;
	private byte premium;

	public Infochannels() {
	}

	public Infochannels(InfochannelsId id, Channels channels, Organizacion organizacion, byte premium) {
		this.id = id;
		this.channels = channels;
		this.organizacion = organizacion;
		this.premium = premium;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idinfo", column = @Column(name = "IDInfo", nullable = false)),
			@AttributeOverride(name = "idchannels", column = @Column(name = "IDChannels", nullable = false)),
			@AttributeOverride(name = "idorganizacion", column = @Column(name = "IDOrganizacion", nullable = false)) })
	public InfochannelsId getId() {
		return this.id;
	}

	public void setId(InfochannelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDChannels", nullable = false, insertable = false, updatable = false)
	public Channels getChannels() {
		return this.channels;
	}

	public void setChannels(Channels channels) {
		this.channels = channels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOrganizacion", nullable = false, insertable = false, updatable = false)
	public Organizacion getOrganizacion() {
		return this.organizacion;
	}

	public void setOrganizacion(Organizacion organizacion) {
		this.organizacion = organizacion;
	}

	@Column(name = "Premium", nullable = false)
	public byte getPremium() {
		return this.premium;
	}

	public void setPremium(byte premium) {
		this.premium = premium;
	}

}
