package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Paquetes generated by hbm2java
 */
@Entity
@Table(name = "paquetes", catalog = "suite")
public class Paquetes implements java.io.Serializable {

	private Integer idpaquete;
	private String nombre;
	private String descripcion;
	private Set<Channels> channelses = new HashSet<Channels>(0);
	private Set<Parrilla> parrillas = new HashSet<Parrilla>(0);

	public Paquetes() {
	}

	public Paquetes(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Paquetes(String nombre, String descripcion, Set<Channels> channelses, Set<Parrilla> parrillas) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.channelses = channelses;
		this.parrillas = parrillas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPaquete", unique = true, nullable = false)
	public Integer getIdpaquete() {
		return this.idpaquete;
	}

	public void setIdpaquete(Integer idpaquete) {
		this.idpaquete = idpaquete;
	}

	@Column(name = "Nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 40)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "containchannelspaquetes", catalog = "suite", joinColumns = {
			@JoinColumn(name = "IDPaquete", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDChannels", nullable = false, updatable = false) })
	public Set<Channels> getChannelses() {
		return this.channelses;
	}

	public void setChannelses(Set<Channels> channelses) {
		this.channelses = channelses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "paqueteses")
	public Set<Parrilla> getParrillas() {
		return this.parrillas;
	}

	public void setParrillas(Set<Parrilla> parrillas) {
		this.parrillas = parrillas;
	}

}
