package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parrilla generated by hbm2java
 */
@Entity
@Table(name = "parrilla", catalog = "suite")
public class Parrilla implements java.io.Serializable {

	private Integer idparrilla;
	private Set<Channels> channelses = new HashSet<Channels>(0);
	private Set<Paquetes> paqueteses = new HashSet<Paquetes>(0);
	private Set<Organizacion> organizacions = new HashSet<Organizacion>(0);

	public Parrilla() {
	}

	public Parrilla(Set<Channels> channelses, Set<Paquetes> paqueteses, Set<Organizacion> organizacions) {
		this.channelses = channelses;
		this.paqueteses = paqueteses;
		this.organizacions = organizacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDParrilla", unique = true, nullable = false)
	public Integer getIdparrilla() {
		return this.idparrilla;
	}

	public void setIdparrilla(Integer idparrilla) {
		this.idparrilla = idparrilla;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "parrillas")
	public Set<Channels> getChannelses() {
		return this.channelses;
	}

	public void setChannelses(Set<Channels> channelses) {
		this.channelses = channelses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "containparripaquetes", catalog = "suite", joinColumns = {
			@JoinColumn(name = "IDParrilla", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDPaquetes", nullable = false, updatable = false) })
	public Set<Paquetes> getPaqueteses() {
		return this.paqueteses;
	}

	public void setPaqueteses(Set<Paquetes> paqueteses) {
		this.paqueteses = paqueteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parrilla")
	public Set<Organizacion> getOrganizacions() {
		return this.organizacions;
	}

	public void setOrganizacions(Set<Organizacion> organizacions) {
		this.organizacions = organizacions;
	}

}
