package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Videos generated by hbm2java
 */
@Entity
@Table(name = "videos", catalog = "suite")
public class Videos implements java.io.Serializable {

	private Integer idvideo;
	private String titulo;
	private Date publish;
	private Date unpublish;
	private String visibilidad;
	private String calidad;
	private Set<Categorias> categoriases = new HashSet<Categorias>(0);

	public Videos() {
	}

	public Videos(String titulo, Date publish, Date unpublish, String visibilidad, String calidad) {
		this.titulo = titulo;
		this.publish = publish;
		this.unpublish = unpublish;
		this.visibilidad = visibilidad;
		this.calidad = calidad;
	}

	public Videos(String titulo, Date publish, Date unpublish, String visibilidad, String calidad,
			Set<Categorias> categoriases) {
		this.titulo = titulo;
		this.publish = publish;
		this.unpublish = unpublish;
		this.visibilidad = visibilidad;
		this.calidad = calidad;
		this.categoriases = categoriases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDVideo", unique = true, nullable = false)
	public Integer getIdvideo() {
		return this.idvideo;
	}

	public void setIdvideo(Integer idvideo) {
		this.idvideo = idvideo;
	}

	@Column(name = "Titulo", nullable = false, length = 30)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Publish", nullable = false, length = 10)
	public Date getPublish() {
		return this.publish;
	}

	public void setPublish(Date publish) {
		this.publish = publish;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Unpublish", nullable = false, length = 10)
	public Date getUnpublish() {
		return this.unpublish;
	}

	public void setUnpublish(Date unpublish) {
		this.unpublish = unpublish;
	}

	@Column(name = "Visibilidad", nullable = false, length = 7)
	public String getVisibilidad() {
		return this.visibilidad;
	}

	public void setVisibilidad(String visibilidad) {
		this.visibilidad = visibilidad;
	}

	@Column(name = "Calidad", nullable = false, length = 3)
	public String getCalidad() {
		return this.calidad;
	}

	public void setCalidad(String calidad) {
		this.calidad = calidad;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "videoses")
	public Set<Categorias> getCategoriases() {
		return this.categoriases;
	}

	public void setCategoriases(Set<Categorias> categoriases) {
		this.categoriases = categoriases;
	}

}
