package model;
// Generated 03-jun-2018 17:29:10 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vod generated by hbm2java
 */
@Entity
@Table(name = "vod", catalog = "suite")
public class Vod implements java.io.Serializable {

	private Integer idvod;
	private int idorganizacion;
	private int idcategoria;

	public Vod() {
	}

	public Vod(int idorganizacion, int idcategoria) {
		this.idorganizacion = idorganizacion;
		this.idcategoria = idcategoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDVod", unique = true, nullable = false)
	public Integer getIdvod() {
		return this.idvod;
	}

	public void setIdvod(Integer idvod) {
		this.idvod = idvod;
	}

	@Column(name = "IDOrganizacion", nullable = false)
	public int getIdorganizacion() {
		return this.idorganizacion;
	}

	public void setIdorganizacion(int idorganizacion) {
		this.idorganizacion = idorganizacion;
	}

	@Column(name = "IDCategoria", nullable = false)
	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

}
